language = "C"

sys_includes = ["stdint.h"]
no_includes = true

[defines]
"target_os = ios" = "TARGET_OS_IOS"
"target_os = macos" = "TARGET_OS_MACOS"

[fn]
rename_args = "CamelCase"

[struct]
rename_fields = "CamelCase"
