name: Publish binaries

on:
  create:
    ref_type: tag
    
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Make binaries
        working-directory: native/dr_libphonenumber
        run: |
          make init
          make ios
          make bindings
          make archive

      - name: Pod lib lint
        working-directory: native/DrLibPhonenumberSwiftBundler
        run: pod lib lint DrLibPhonenumberSwiftBundler.podspec

#      - name: Zip ios artifacts
#        working-directory: native/dr_libphonenumber
#        run: |
#          zip -r artifacts.zip target/universal
#          zip -ru artifacts.zip target/bindings.h
          
      # https://github.com/ncipollo/release-action
#      - name: Create a release
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "native/dr_libphonenumber/artifacts.zip"
#          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Cleanup
        working-directory: native/dr_libphonenumber
        run: make clean
