name: Publish to CocoaPods trunk

on:
  create:
    ref_type: tag
    
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Make binaries
        working-directory: dr_libphonenumber
        run: |
          make init
          make ios
          make bindings
          make archive

      - name: Deploy to Cocoapod
        working-directory: DrLibPhonenumberSwiftBundler
        run: | 
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
        env: 
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          
      - name: Cleanup
        working-directory: dr_libphonenumber
        run: make clean
